version: '2'
services:
  web:
    build: .  # use Dockerfile
    environment:
      - FLASK_ENV=production

      - VIRTUAL_HOST=photos.broox.com
      - LETSENCRYPT_HOST=photos.broox.com
      - LETSENCRYPT_EMAIL=derek@broox.com
    expose:
      - "5000"
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./app:/app
    networks:
      - default

networks:
  default:
    external:
      name: nginx-proxy
