version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: production.dockerfile
    command: python3 /app/app.py
    environment:
      - FLASK_ENV=production
      - VIRTUAL_HOST=photos.broox.com
      - LETSENCRYPT_HOST=photos.broox.com
      - LETSENCRYPT_EMAIL=derek@broox.com
    expose:
      - "5000"
    ports:
      - "5000:5000"
    restart: always
    networks:
      - default

networks:
  default:
    external:
      name: nginx-proxy

